package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Saturday, October 26, 2019 9:14:16 PM PKT
*/

public interface HelloOperations 
{
  String sayHello (int tableNumber, int printTime);
  void shutdown ();
} // interface HelloOperations
